# -*- coding: utf-8 -*-
"""Perbandingan Model Vision Transformer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-K-bOgrWERR7zX3ECBUEEvCw7dgXFG0

#**SETUP LINGKUNGAN**
"""

!pip install timm torchinfo scikit-learn tqdm

import torch
from torchvision import datasets, transforms
from torch.utils.data import Dataset, DataLoader, random_split
import torch.nn as nn
import torch.optim as optim
from torchinfo import summary
import timm
from sklearn.metrics import classification_report, confusion_matrix
import time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Menggunakan perangkat: {device}")

"""#**PRE PROCESSING**"""

IMAGE_SIZE = 224
NORM_MEAN = (0.485, 0.456, 0.406)
NORM_STD = (0.229, 0.224, 0.225)
BATCH_SIZE = 32

train_transforms = transforms.Compose([
    transforms.Resize(IMAGE_SIZE),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(NORM_MEAN, NORM_STD)
])

val_transforms = transforms.Compose([
    transforms.Resize(IMAGE_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(NORM_MEAN, NORM_STD)
])

full_train_dataset = datasets.CIFAR10(
    root='./data',
    train=True,
    download=True, #
    transform=train_transforms
)

test_dataset = datasets.CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=val_transforms
)

NUM_CLASSES = len(full_train_dataset.classes)

TRAIN_RATIO = 0.8
train_size = int(TRAIN_RATIO * len(full_train_dataset))
val_size = len(full_train_dataset) - train_size

train_dataset, val_dataset_raw = random_split(
    full_train_dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset_raw, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print(f"\nDataset CIFAR-10 berhasil dimuat dan dibagi:")
print(f"  Jumlah Kelas: {NUM_CLASSES} (Memenuhi syarat minimal 3 kelas tugas)")
print(f"  Data Training (80%): {len(train_dataset)} sampel")
print(f"  Data Validation (20%): {len(val_dataset_raw)} sampel")
print(f"  Data Test Set CIFAR-10: {len(test_dataset)} sampel")

"""#**MODEL VIT, DEIT, DAN SWIN**"""

VIT_MODEL = 'vit_base_patch16_224'
DEIT_MODEL = 'deit_base_patch16_224'
SWIN_MODEL = 'swin_base_patch4_window7_224'
MODEL_NAMES = [VIT_MODEL, DEIT_MODEL, SWIN_MODEL]
LOADED_MODELS = {}
PARAM_METRICS = []

def get_model_and_metrics(model_name, num_classes):
    model = timm.create_model(model_name, pretrained=True, num_classes=num_classes)
    model.to(device)
    model_summary = summary(model, input_size=(BATCH_SIZE, 3, IMAGE_SIZE, IMAGE_SIZE), verbose=0)

    metrics = {
        'Model': model_name,
        'Total Parameter': model_summary.total_params,
        'Trainable Parameter': model_summary.trainable_params,
        'Non-Trainable Parameter': model_summary.total_params - model_summary.trainable_params,
        'Ukuran Model (MB)': model_summary.total_param_bytes / (1024 * 1024)
    }

    print(f"\n--- Ringkasan Parameter: {model_name} ---")
    for key, value in metrics.items():
        if key == 'Model':
            print(f"{key}: {value}")
        elif 'Parameter' in key:
            print(f"{key}: {value:,}")
        else:
            print(f"{key}: {value:.2f} MB")

    return model, metrics

for name in MODEL_NAMES:
    model, metrics = get_model_and_metrics(name, NUM_CLASSES)
    LOADED_MODELS[name] = model
    PARAM_METRICS.append(metrics)

"""#**TRAINING ViT**"""

LEARNING_RATE = 1e-5
NUM_EPOCHS = 5
OPTIMIZER = optim.AdamW
CRITERION = nn.CrossEntropyLoss()

model_to_train_name = VIT_MODEL
model_to_train = LOADED_MODELS[model_to_train_name]
optimizer = OPTIMIZER(model_to_train.parameters(), lr=LEARNING_RATE)

history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}

def train_one_epoch(model, dataloader, criterion, optimizer):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    dataloader_progress = tqdm(dataloader, desc="Training")

    for inputs, labels in dataloader_progress:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        current_loss = total_loss / total
        current_acc = 100 * correct / total
        dataloader_progress.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.2f}%')

    return total_loss / total, 100 * correct / total

def validate_one_epoch(model, dataloader, criterion):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    with torch.no_grad():
        dataloader_progress = tqdm(dataloader, desc="Validation")

        for inputs, labels in dataloader_progress: # Gunakan dataloader yang sudah dibungkus
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            total_loss += loss.item() * inputs.size(0)

            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            current_loss = total_loss / total
            current_acc = 100 * correct / total
            dataloader_progress.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.2f}%')

    return total_loss / total, 100 * correct / total

# --- LOOP PELATIHAN ---
print(f"\nMemulai Training Model: {model_to_train_name}...")

for epoch in range(NUM_EPOCHS):
    train_loss, train_acc = train_one_epoch(model_to_train, train_loader, CRITERION, optimizer)
    val_loss, val_acc = validate_one_epoch(model_to_train, val_loader, CRITERION)

    # Simpan hasil untuk kurva pembelajaran
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Epoch {epoch+1}/{NUM_EPOCHS} | Train Loss: {train_loss:.4f} (Acc: {train_acc:.2f}%) | Val Loss: {val_loss:.4f} (Acc: {val_acc:.2f}%)")

# Simpan model yang sudah dilatih
LOADED_MODELS[model_to_train_name] = model_to_train
print(f"\n Training {model_to_train_name} SELESAI. Model disimpan.")

# VISUALISASI KURVA
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Validation Loss')
plt.title(f'{model_to_train_name} - Loss Curve')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Accuracy')
plt.plot(history['val_acc'], label='Validation Accuracy')
plt.title(f'{model_to_train_name} - Accuracy Curve')
plt.legend()
plt.show()

model_to_save_name = VIT_MODEL
model_save_path = f"{model_to_save_name}_final_weights.pth"
torch.save(model_to_train.state_dict(), model_save_path)
print(f"Model {model_to_save_name} berhasil disimpan ke: {model_save_path}")

"""#**METRIK PERFORMA ViT**"""

model_to_eval_name = VIT_MODEL
model_to_eval = LOADED_MODELS[model_to_eval_name]

def evaluate_and_time(model, dataloader, dataset, model_name, output_filename="predictions_output.csv"):
    model.eval()

    all_preds = []
    all_labels = []
    inference_times_ms = []

    print("Memulai Warm-up...")
    with torch.no_grad():
        for i, (inputs, labels) in enumerate(dataloader):
            if i < 5:
                inputs = inputs.to(device)
                _ = model(inputs)
            else:
                break
    print("Warm-up Selesai. Memulai pengukuran inferensi...")

    # Pengukuran Inferensi
    total_samples = 0
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            total_samples += labels.size(0)

            # Waktu Inferensi per batch
            if device.type == 'cuda':
                starter, ender = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
                starter.record()
                outputs = model(inputs)
                ender.record()
                torch.cuda.synchronize()
                curr_time = starter.elapsed_time(ender)
            else:
                t0 = time.time()
                outputs = model(inputs)
                t1 = time.time()
                curr_time = (t1 - t0) * 1000

            inference_times_ms.append(curr_time)

            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # --- Menyimpan File Hasil Prediksi ---
    results_df = pd.DataFrame({
        'True_Label_ID': all_labels,
        'Predicted_Label_ID': all_preds,
        'True_Label_Name': [dataset.classes[l] for l in all_labels],
        'Predicted_Label_Name': [dataset.classes[p] for p in all_preds]
    })

    # Simpan DataFrame ke file CSV
    results_df.to_csv(output_filename, index=False)
    print(f"\nFile hasil prediksi tersimpan di: {output_filename}")


    # --- Perhitungan Metrik Inferensi ---
    total_time_ms = sum(inference_times_ms)
    avg_time_per_image_ms = total_time_ms / total_samples
    throughput_ips = total_samples / (total_time_ms / 1000)

    print(f"\n--- Hasil Inferensi {model_name} ---")
    print(f"Hardware Digunakan: {device}")
    print(f"Total Sampel Inferensi: {total_samples}")
    print(f"Waktu Rata-rata per Gambar: {avg_time_per_image_ms:.3f} ms")
    print(f"Throughput: {throughput_ips:.2f} gambar/detik")

    # --- Perhitungan Metrik Performa ---
    print("\n--- Classification Report (Performance Metrics) ---")
    report = classification_report(all_labels, all_preds, target_names=dataset.classes, output_dict=False)
    print(report)

    # Confusion Matrix (untuk visualisasi)
    conf_matrix = confusion_matrix(all_labels, all_preds)

    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
                xticklabels=dataset.classes, yticklabels=dataset.classes)
    plt.title(f'Confusion Matrix: {model_name}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

# Jalankan evaluasi untuk model yang dipilih
output_file = f"predictions_{model_to_eval_name}.csv"
evaluate_and_time(model_to_eval, val_loader, full_train_dataset, model_to_eval_name, output_file)

"""#**TRAINING DeiT**

"""

LEARNING_RATE = 1e-5
NUM_EPOCHS = 5
OPTIMIZER = optim.AdamW
CRITERION = nn.CrossEntropyLoss()

model_to_train_name = DEIT_MODEL
model_to_train = LOADED_MODELS[model_to_train_name]
optimizer = OPTIMIZER(model_to_train.parameters(), lr=LEARNING_RATE)

history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}

def train_one_epoch(model, dataloader, criterion, optimizer):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    dataloader_progress = tqdm(dataloader, desc="Training")

    for inputs, labels in dataloader_progress:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        current_loss = total_loss / total
        current_acc = 100 * correct / total
        dataloader_progress.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.2f}%')

    return total_loss / total, 100 * correct / total

def validate_one_epoch(model, dataloader, criterion):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    with torch.no_grad():
        dataloader_progress = tqdm(dataloader, desc="Validation")

        for inputs, labels in dataloader_progress: # Gunakan dataloader yang sudah dibungkus
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            total_loss += loss.item() * inputs.size(0)

            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            current_loss = total_loss / total
            current_acc = 100 * correct / total
            dataloader_progress.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.2f}%')

    return total_loss / total, 100 * correct / total

# --- LOOP PELATIHAN ---
print(f"\nMemulai Training Model: {model_to_train_name}...")

for epoch in range(NUM_EPOCHS):
    train_loss, train_acc = train_one_epoch(model_to_train, train_loader, CRITERION, optimizer)
    val_loss, val_acc = validate_one_epoch(model_to_train, val_loader, CRITERION)

    # Simpan hasil untuk kurva pembelajaran
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Epoch {epoch+1}/{NUM_EPOCHS} | Train Loss: {train_loss:.4f} (Acc: {train_acc:.2f}%) | Val Loss: {val_loss:.4f} (Acc: {val_acc:.2f}%)")

# Simpan model yang sudah dilatih
LOADED_MODELS[model_to_train_name] = model_to_train
print(f"\n Training {model_to_train_name} SELESAI. Model disimpan.")

# VISUALISASI KURVA
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Validation Loss')
plt.title(f'{model_to_train_name} - Loss Curve')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Accuracy')
plt.plot(history['val_acc'], label='Validation Accuracy')
plt.title(f'{model_to_train_name} - Accuracy Curve')
plt.legend()
plt.show()

model_to_save_name = DEIT_MODEL
model_save_path = f"{model_to_save_name}_final_weights.pth"
torch.save(model_to_train.state_dict(), model_save_path)
print(f"Model {model_to_save_name} berhasil disimpan ke: {model_save_path}")

"""#**METRIK PERFORMA DeiT**"""

model_to_eval_name = DEIT_MODEL
model_to_eval = LOADED_MODELS[model_to_eval_name]

def evaluate_and_time(model, dataloader, dataset, model_name, output_filename="predictions_output.csv"):
    model.eval()

    all_preds = []
    all_labels = []
    inference_times_ms = []

    print("Memulai Warm-up...")
    with torch.no_grad():
        for i, (inputs, labels) in enumerate(dataloader):
            if i < 5:
                inputs = inputs.to(device)
                _ = model(inputs)
            else:
                break
    print("Warm-up Selesai. Memulai pengukuran inferensi...")

    # Pengukuran Inferensi
    total_samples = 0
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            total_samples += labels.size(0)

            # Waktu Inferensi per batch
            if device.type == 'cuda':
                starter, ender = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
                starter.record()
                outputs = model(inputs)
                ender.record()
                torch.cuda.synchronize()
                curr_time = starter.elapsed_time(ender)
            else:
                t0 = time.time()
                outputs = model(inputs)
                t1 = time.time()
                curr_time = (t1 - t0) * 1000

            inference_times_ms.append(curr_time)

            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # --- Menyimpan File Hasil Prediksi ---
    results_df = pd.DataFrame({
        'True_Label_ID': all_labels,
        'Predicted_Label_ID': all_preds,
        'True_Label_Name': [dataset.classes[l] for l in all_labels],
        'Predicted_Label_Name': [dataset.classes[p] for p in all_preds]
    })

    # Simpan DataFrame ke file CSV
    results_df.to_csv(output_filename, index=False)
    print(f"\nFile hasil prediksi tersimpan di: {output_filename}")


    # --- Perhitungan Metrik Inferensi ---
    total_time_ms = sum(inference_times_ms)
    avg_time_per_image_ms = total_time_ms / total_samples
    throughput_ips = total_samples / (total_time_ms / 1000)

    print(f"\n--- Hasil Inferensi {model_name} ---")
    print(f"Hardware Digunakan: {device}")
    print(f"Total Sampel Inferensi: {total_samples}")
    print(f"Waktu Rata-rata per Gambar: {avg_time_per_image_ms:.3f} ms")
    print(f"Throughput: {throughput_ips:.2f} gambar/detik")

    # --- Perhitungan Metrik Performa ---
    print("\n--- Classification Report (Performance Metrics) ---")
    report = classification_report(all_labels, all_preds, target_names=dataset.classes, output_dict=False)
    print(report)

    # Confusion Matrix (untuk visualisasi)
    conf_matrix = confusion_matrix(all_labels, all_preds)

    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
                xticklabels=dataset.classes, yticklabels=dataset.classes)
    plt.title(f'Confusion Matrix: {model_name}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

# Jalankan evaluasi untuk model yang dipilih
output_file = f"predictions_{model_to_eval_name}.csv"
evaluate_and_time(model_to_eval, val_loader, full_train_dataset, model_to_eval_name, output_file)

"""#**TRAINING Swin**"""

LEARNING_RATE = 1e-5
NUM_EPOCHS = 5
OPTIMIZER = optim.AdamW
CRITERION = nn.CrossEntropyLoss()

model_to_train_name = SWIN_MODEL
model_to_train = LOADED_MODELS[model_to_train_name]
optimizer = OPTIMIZER(model_to_train.parameters(), lr=LEARNING_RATE)

history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}

def train_one_epoch(model, dataloader, criterion, optimizer):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    dataloader_progress = tqdm(dataloader, desc="Training")

    for inputs, labels in dataloader_progress:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        current_loss = total_loss / total
        current_acc = 100 * correct / total
        dataloader_progress.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.2f}%')

    return total_loss / total, 100 * correct / total

def validate_one_epoch(model, dataloader, criterion):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    with torch.no_grad():
        dataloader_progress = tqdm(dataloader, desc="Validation")

        for inputs, labels in dataloader_progress: # Gunakan dataloader yang sudah dibungkus
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            total_loss += loss.item() * inputs.size(0)

            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            current_loss = total_loss / total
            current_acc = 100 * correct / total
            dataloader_progress.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.2f}%')

    return total_loss / total, 100 * correct / total

# --- LOOP PELATIHAN ---
print(f"\nMemulai Training Model: {model_to_train_name}...")

for epoch in range(NUM_EPOCHS):
    train_loss, train_acc = train_one_epoch(model_to_train, train_loader, CRITERION, optimizer)
    val_loss, val_acc = validate_one_epoch(model_to_train, val_loader, CRITERION)

    # Simpan hasil untuk kurva pembelajaran
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Epoch {epoch+1}/{NUM_EPOCHS} | Train Loss: {train_loss:.4f} (Acc: {train_acc:.2f}%) | Val Loss: {val_loss:.4f} (Acc: {val_acc:.2f}%)")

# Simpan model yang sudah dilatih
LOADED_MODELS[model_to_train_name] = model_to_train
print(f"\n Training {model_to_train_name} SELESAI. Model disimpan.")

# VISUALISASI KURVA
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Validation Loss')
plt.title(f'{model_to_train_name} - Loss Curve')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Accuracy')
plt.plot(history['val_acc'], label='Validation Accuracy')
plt.title(f'{model_to_train_name} - Accuracy Curve')
plt.legend()
plt.show()

model_to_save_name = SWIN_MODEL
model_save_path = f"{model_to_save_name}_final_weights.pth"
torch.save(model_to_train.state_dict(), model_save_path)
print(f"Model {model_to_save_name} berhasil disimpan ke: {model_save_path}")

"""#**METRIK PERFORMA Swin**"""

model_to_eval_name = SWIN_MODEL
model_to_eval = LOADED_MODELS[model_to_eval_name]

def evaluate_and_time(model, dataloader, dataset, model_name, output_filename="predictions_output.csv"):
    model.eval()

    all_preds = []
    all_labels = []
    inference_times_ms = []

    print("Memulai Warm-up...")
    with torch.no_grad():
        for i, (inputs, labels) in enumerate(dataloader):
            if i < 5:
                inputs = inputs.to(device)
                _ = model(inputs)
            else:
                break
    print("Warm-up Selesai. Memulai pengukuran inferensi...")

    # Pengukuran Inferensi
    total_samples = 0
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            total_samples += labels.size(0)

            # Waktu Inferensi per batch
            if device.type == 'cuda':
                starter, ender = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
                starter.record()
                outputs = model(inputs)
                ender.record()
                torch.cuda.synchronize()
                curr_time = starter.elapsed_time(ender)
            else:
                t0 = time.time()
                outputs = model(inputs)
                t1 = time.time()
                curr_time = (t1 - t0) * 1000

            inference_times_ms.append(curr_time)

            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # --- Menyimpan File Hasil Prediksi ---
    results_df = pd.DataFrame({
        'True_Label_ID': all_labels,
        'Predicted_Label_ID': all_preds,
        'True_Label_Name': [dataset.classes[l] for l in all_labels],
        'Predicted_Label_Name': [dataset.classes[p] for p in all_preds]
    })

    # Simpan DataFrame ke file CSV
    results_df.to_csv(output_filename, index=False)
    print(f"\nFile hasil prediksi tersimpan di: {output_filename}")


    # --- Perhitungan Metrik Inferensi ---
    total_time_ms = sum(inference_times_ms)
    avg_time_per_image_ms = total_time_ms / total_samples
    throughput_ips = total_samples / (total_time_ms / 1000)

    print(f"\n--- Hasil Inferensi {model_name} ---")
    print(f"Hardware Digunakan: {device}")
    print(f"Total Sampel Inferensi: {total_samples}")
    print(f"Waktu Rata-rata per Gambar: {avg_time_per_image_ms:.3f} ms")
    print(f"Throughput: {throughput_ips:.2f} gambar/detik")

    # --- Perhitungan Metrik Performa ---
    print("\n--- Classification Report (Performance Metrics) ---")
    report = classification_report(all_labels, all_preds, target_names=dataset.classes, output_dict=False)
    print(report)

    # Confusion Matrix (untuk visualisasi)
    conf_matrix = confusion_matrix(all_labels, all_preds)

    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
                xticklabels=dataset.classes, yticklabels=dataset.classes)
    plt.title(f'Confusion Matrix: {model_name}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

# Jalankan evaluasi untuk model yang dipilih
output_file = f"predictions_{model_to_eval_name}.csv"
evaluate_and_time(model_to_eval, val_loader, full_train_dataset, model_to_eval_name, output_file)